version: '3.1'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=picpaydb
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: